[package]
name = "gtfout"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.2.1"
log = "0.4.19"
pretty_env_logger = "0.5.0"
serde = { version = "1.0.158", features = ["derive"] }
